POST http://localhost:5000/user/register
Content-Type: application/json

{
  "email": "ichigo@gmail.com",
  "password": "123"
}
###648faa66ab66b5beb6cd9c77

POST http://localhost:5000/user/login
Content-Type: application/json

{
  "email": "ichigo@gmail.com",
  "password": "123"
}
###
POST http://localhost:5000/user/login
Content-Type: application/json

{
  "email": "frostisnotgay@gmail.com",
  "password": "123456"
}
###648a506a53f1b2315b4944bc

POST http://localhost:5000/user/register
Content-Type: application/json

{
  "email": "browney@gmail.com",
  "password": "123",
  "role": false
}
###

GET http://localhost:5000/user/register
Content-Type: application/json

{}
###

GET /users/:userId
Content-Type: application/json

{}
###

UPDATE /users/:userId
Content-Type: application/json

{
  "email": "updated.email@example.com"
}
###

DELETE /users/:userId
Content-Type: application/json

{}
