POST http://localhost:5000/admin/
Content-Type: application/json

{
  "user": "648a504c53f1b2315b4944b8",
  "adminID": "A123456",
  "firstName": "John",
  "lastName": "Doe",
  "contactEmail": "john.doe@example.com",
  "control": true,
  "inCharge": ["Department A", "Department B"],
  "created": "2022-06-15"
}
###

POST http://localhost:5000/admin/
Content-Type: application/json

{
  "user": ["648a506a53f1b2315b4944bc"],
  "adminID": "A789012",
  "firstName": "Jane",
  "lastName": "Smith",
  "contactEmail": "jane.smith@example.com",
  "control": false,
  "inCharge": ["Department C"],
  "created": "2021-12-01"
}
###

POST http://localhost:5000/admin/
Content-Type: application/json

{
  "user": ["648a506a53f1b2315b4944bc"],
  "adminID": "A345678",
  "firstName": "David",
  "lastName": "Brown",
  "contactEmail": "david.brown@example.com",
  "control": true,
  "inCharge": ["Department D", "Department E"],
  "created": "2023-01-20"
}
###

GET http://localhost:5000/admin/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDhhN2FjYTU5ZmZlYTAxNjkxMmU5ODAiLCJpYXQiOjE2ODY3OTk1NDMsImV4cCI6MTY4NjgwMzE0M30.SWu4EM1jKXfLyzkhzsJujbnh0N0M84NgquNvikyGiRg

###

GET /admins/:adminId
Content-Type: application/json

{}
###

PATCH http://localhost:5000/admin/
Content-Type: application/json

{
  "firstName": "UpdatedFirstName"
}
###

DELETE /admins/:adminId
Content-Type: application/json

{}
