###
POST http://localhost:5000/student/
Content-Type: application/json

{
  "user": "6495a691ec3caa46efaddfd4",
  "name": "John Doe",
  "email": "john.doe@example.com",
  "birthDate": "1990-01-01",
  "level": "Beginner",
  "country": "USA",
  "city": "New York",
  "phoneNumber": "1234567890"
}
